### ISSUE TITLE
Peer-to-peer morning review

### ISSUE THREAD

**Issue by Yothu** [Sahar-AbdelSamad/To-do-list#14]
I would recommend putting more detail into what the test actually does, for example:
https://github.com/Sahar-AbdelSamad/To-do-list/blob/c6ed1c4fa46b324e6b7c7566ad465b3943d87dc8/src/tests/__tests__/addDelete.test.js#L19-L23
Here **the test is actually testing if the task list length is 0**, and that _implies_ that the task was deleted, it is necessary to make the description test a statement as objective as possible, in this particular test I would recommend  _The length of the task list that has a task inside it after removing a task is 0_, in the suggestion I describe the start of the test and the expected result of the test.
The same issue can be found in every test.

**Comment by Sahar-AbdelSamad** [comment]
Well noted. Thank you :smile:
