### ISSUE TITLE
Peer to peer morning review 2

### ISSUE THREAD

**Issue by Yothu** [Sahar-AbdelSamad/To-do-list#15]
I would recommend doing the `add`, `modify`, `delete`, and `drag` functions without reloading the page every time they are summoned.

**Comment by gdumani** [comment]
Excellent job. Nice implementation of the drag and drop functions

**Comment by Sahar-AbdelSamad** [comment]
> I would recommend doing the `add`, `modify`, `delete`, and `drag` functions without reloading the page every time they are summoned.

Well noted. Thank you :smile:

**Comment by Sahar-AbdelSamad** [comment]
> Excellent job. Nice implementation of the drag and drop functions

Thank you :smile:
